### PR TITLE
Fix typo in salary field name

### PR DESCRIPTION
**Pull request by elalemanyo**
### What is the issue:
https://github.com/Absolventa/uno/issues/6089

https://github.com/Absolventa/uno/pull/8133

### CODE REVIEW

**Review by Tossmann — APPROVED** [review]
Good job :P

**Comment by Tossmann** [comment]
I'm not sure why I still have access here 🤷 Could you please remove me. Discovered it by accident

**Comment by elalemanyo** [comment]
> I'm not sure why I still have access here 🤷 Could you please remove me. Discovered it by accident

@Tossmann this is a public repo 😉

**Comment by dansch** [comment]
@Tossmann Good to have you back! 😄

**Comment by Tossmann** [comment]
Ah I see. I was just wondering how I can still give reviews on it 😃 I unsubscribed for now, but if I need api docs I know where to look 😎

**Pull request merged**
